# Use root/example as user/password credentials
version: '3.1'
name: tks-user-service
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "7451:27017"

  rabbitmq:
    container_name: 'guide-rabbit'
    image: "rabbitmq:3-management"
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'